name: JepsenWorkflow
env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1
concurrency:
  group: jepsen
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  workflow_call:
jobs:
  KeeperJepsenRelease:
    runs-on: [self-hosted, style-checker]
    steps:
      - name: Check out repository code
        uses: ClickHouse/checkout@v1
        with:
          clear-repository: true
          ref: ${{ github.event.after }}
          submodules: false
          fetch-depth: 1
          filter: tree:0
      - name: Set build envs
        run: |
          cat >> "$GITHUB_ENV" << 'EOF'
          CHECK_NAME="Jepsen keeper check"
          EOF
      - name: Common setup
        uses: ./.github/actions/common_setup
        with:
          job_type: test
      - name: Run
        run: |
          cd "./tests/ci"
          python3 ./jepsen_check.py keeper
      - name: Clean
        if: always()
        uses: ./.github/actions/clean
        # ServerJepsenRelease:
        #   runs-on: [self-hosted, style-checker]
        #   steps:
        #     - name: Check out repository code
        #       uses: ClickHouse/checkout@v1
        #       with:
        #         clear-repository: true
        #         ref: ${{ github.event.after }}
        #         submodules: false
        #         fetch-depth: 1
        #         filter: tree:0
        #     - name: Set build envs
        #       run: |
        #         cat >> "$GITHUB_ENV" << 'EOF'
        #         CHECK_NAME="Jepsen server check"
        #         EOF
        #     - name: Common setup
        #       uses: ./.github/actions/common_setup
        #       with:
        #         job_type: test
        #     - name: Run
        #       run: |
        #         cd "./tests/ci"
        #         python3 ./jepsen_check.py server
        #     - name: Clean
        #       if: always()
        #       uses: ./.github/actions/clean
